name: Upload PDF or EPUB to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支上的提交

  workflow_dispatch:  # 允许手动触发

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 创建 uploads 目录（如果不存在）
        run: mkdir -p uploads

      - name: 复制文件（PDF 或 EPUB）
        run: |
          if [ -d "temp_uploads" ]; then
            cp -r temp_uploads/* uploads/
            rm -rf temp_uploads  # 清空临时上传目录
          fi

      - name: 提交更改
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add uploads/
          git commit -m "上传新的 PDF 或 EPUB 文件" || echo "No changes to commit"
          git push
